### ISSUE TITLE
Install fails with php8

### ISSUE THREAD

**Issue by grosseskino** [mixerapi/jwt-auth#1]
Hi.

I just tried to install and updated to php8 (as it is required).
Install fails:
 Problem 1
    - symfony/service-contracts v1.1.2 requires php ^7.1.3 -> your php version (8.0.20) does not satisfy that requirement.
    - composer/composer 2.3.7 requires symfony/console ^5.4.7 || ^6.0.7 -> satisfiable by symfony/console[v5.4.9].
    - cakephp/debug_kit 4.8.1 requires composer/composer ^1.3 | ^2.0 -> satisfiable by composer/composer[2.3.7].
    - symfony/console v5.4.9 requires symfony/service-contracts ^1.1|^2|^3 -> satisfiable by symfony/service-contracts[v1.1.2].
    - cakephp/debug_kit is locked to version 4.8.1 and an update of this package was not requested.

any suggestions?

**Comment by cnizzardini** [comment]
Hi @grosseskino I just tried on a fresh CakePHP project running `PHP 8.0.13 (cli) (built: Nov 19 2021 22:37:59) ( NTS )` and it worked (see below for output) so I think the package is fine. 

It looks like there are some issues in your dependency chain. Have you tried running `composer update -W` to update all your dependencies. If you are still having problems can do post results of `composer show -i`?

Output from my install:

```console
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^1.1 for mixerapi/jwt-auth
./composer.json has been updated
Running composer update mixerapi/jwt-auth
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking cakephp/authentication (2.9.0)
  - Locking firebase/php-jwt (v5.5.1)
  - Locking mixerapi/jwt-auth (v1.1.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading firebase/php-jwt (v5.5.1)
  - Downloading cakephp/authentication (2.9.0)
  - Downloading mixerapi/jwt-auth (v1.1.2)
  - Installing firebase/php-jwt (v5.5.1): Extracting archive
  - Installing cakephp/authentication (2.9.0): Extracting archive
  - Installing mixerapi/jwt-auth (v1.1.2): Extracting archive

```

**Comment by grosseskino** [comment]
composer update -W 
worked fine with the update, thanks :)
